BulkyBookWeb/Areas/Admin/Controllers/CompanyController.cs
using BulkyBook.DataAccess.Repositry.IRepositry;
using BulkyBook.Models;
//using BulkyBook.Models.ViewModel;
//using BulkyBookWeb.Data;
using BulkyBook.DataAccess.Data;

using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using BulkyBook.Models.ViewModels;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace BulkyBookWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CompanyController : Controller
    {
        //private readonly ICategoryRepositry _Db;
        private readonly IUnitOfWork _unitofwork;

        public CompanyController(IUnitOfWork unitofwork)
        {
            //_Db = db;
            _unitofwork = unitofwork;

        }

        public IActionResult Index()
        {
            //IEnumerable<Category> categories = _Db.GetAll();
            //IEnumerable<Product> products = _unitofwork.Product.GetAll();

            //return View(products);
            return View();
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Company obj)
        {


            if (ModelState.IsValid)
            {
                //_Db.Add(obj);
                _unitofwork.Company.Add(obj);
                _unitofwork.Save();
                TempData["Success"] = "Created Successfuly";
                return RedirectToAction("Index");
            }



            return View(obj);
        }
        [HttpGet]
        public IActionResult Details(int id)
        {
            //var details = _Db.Categories.Where(x => x.Id == id).FirstOrDefault();
            var details = _unitofwork.Company.GetFirstorDefault(x => x.Id == id);

            return View(details);
        }

        //Upsert means to update
        [HttpGet]
        public IActionResult Upsert(int? id)
        {
            Company company = new();

            if (id == null || id == 0)
            {
                return View(company);
            }
            else
            {

                company = _unitofwork.Company.GetFirstorDefault(u => u.Id == id);
                return View(company);


            }



        }

        [HttpPost]
        public IActionResult Upsert(Company obj)
        {

            if (ModelState.IsValid)
            {
                if (obj.Id == 0)
                {
                    _unitofwork.Company.Add(obj);
                    TempData["Success"] = "Company Add Successfuly";
                }
                else
                {
                    _unitofwork.Company.Update(obj);
                    TempData["Success"] = "Company Updated Successfuly";
                }

            }
            _unitofwork.Save();
            return RedirectToAction("Index");

        }

        #region
        [HttpGet]
        public IActionResult GetAll()
        {
            var companiesList = _unitofwork.Company.GetAll();
            return Json(new { data = companiesList });
        }


        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var obj = _unitofwork.Company.GetFirstorDefault(u => u.Id == id);
            if (obj == null)
            {
                return Json(new { success = false, message = "Error While Deleting" });
            }
            _unitofwork.Company.Remove(obj);
            _unitofwork.Save();
            return Json(new { success = true, message = "Deleted Successfuly" });

        }
        #endregion


    }
}

BulkyBookWeb/Areas/Admin/Controllers/CoverTypeController.cs
using BulkyBook.DataAccess.Repositry.IRepositry;
using BulkyBook.Models;
//using BulkyBookWeb.Data;
using BulkyBook.DataAccess.Data;

using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BulkyBookWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CoverTypeController : Controller
    {
        //private readonly ICategoryRepositry _Db;
        private readonly IUnitOfWork _unitofwork;
        public CoverTypeController(IUnitOfWork unitofwork)
        {
            //_Db = db;
            _unitofwork = unitofwork;
        }

        public IActionResult Index()
        {
            //IEnumerable<Category> categories = _Db.GetAll();
            IEnumerable<CoverType> covertypes = _unitofwork.CoverType.GetAll();

            return View(covertypes);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CoverType obj)
        {
           

            if (ModelState.IsValid)
            {
                //_Db.Add(obj);
                _unitofwork.CoverType.Add(obj);
                _unitofwork.Save();
                TempData["Success"] = "The Type of Cover Created Successfuly";
                return RedirectToAction("Index");
            }



            return View(obj);
        }
        [HttpGet]
        public IActionResult Details(int id)
        {
            //var details = _Db.Categories.Where(x => x.Id == id).FirstOrDefault();
            var details = _unitofwork.CoverType.GetFirstorDefault(x => x.Id == id);

            return View(details);
        }
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            //var edit = _Db.GetFirstorDefault(x => x.Name == "id");
            var edit = _unitofwork.CoverType.GetFirstorDefault(x => x.Id == id);

            if (edit == null)
            {
                return NotFound();
            }

            return View(edit);
        }

        [HttpPost]
        public IActionResult Edit(CoverType ct)
        {
            _unitofwork.CoverType.Update(ct);
            _unitofwork.Save();
            TempData["Success"] = "Cover Type Updated Successfuly";
            return RedirectToAction("Index");
        }


        [HttpGet]
        public IActionResult Delete(int? id)
        {
            //var edit = _Db.Categories.Where(x => x.Id == id).FirstOrDefault();
            var covertypefromdbfirst = _unitofwork.CoverType.GetFirstorDefault(x => x.Id == id);
            if (covertypefromdbfirst == null)
            {
                return NotFound();
            }

            return View(covertypefromdbfirst);
        }

        [HttpPost]
        public IActionResult Delete(CoverType ct)
        {
            _unitofwork.CoverType.Remove(ct);
            _unitofwork.Save();
            TempData["Success"] = "Cover Type Deleted Successfuly";
            return RedirectToAction("Index");
        }


    }
}

BulkyBookWeb/Areas/Admin/Controllers/ProductController.cs
using BulkyBook.DataAccess.Repositry.IRepositry;
using BulkyBook.Models;
//using BulkyBook.Models.ViewModel;
//using BulkyBookWeb.Data;
using BulkyBook.DataAccess.Data;

using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using BulkyBook.Models.ViewModels;


namespace BulkyBookWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductController : Controller
    {
        //private readonly ICategoryRepositry _Db;
        private readonly IUnitOfWork _unitofwork;
        private readonly IWebHostEnvironment _hostEnvironment;
        public ProductController(IUnitOfWork unitofwork, IWebHostEnvironment hostEnvironment)
        {
            //_Db = db;
            _unitofwork = unitofwork;
            _hostEnvironment = hostEnvironment;
        }

        public IActionResult Index()
        {
            //IEnumerable<Category> categories = _Db.GetAll();
            //IEnumerable<Product> products = _unitofwork.Product.GetAll();

            //return View(products);
            return View();
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Product obj)
        {


            if (ModelState.IsValid)
            {
                //_Db.Add(obj);
                _unitofwork.Product.Add(obj);
                _unitofwork.Save();
                TempData["Success"] = "The Type of Cover Created Successfuly";
                return RedirectToAction("Index");
            }



            return View(obj);
        }
        [HttpGet]
        public IActionResult Details(int id)
        {
            //var details = _Db.Categories.Where(x => x.Id == id).FirstOrDefault();
            var details = _unitofwork.Product.GetFirstorDefault(x => x.Id == id);

            return View(details);
        }

        //Upsert means to update
        [HttpGet]
        public IActionResult Upsert(int? id)
        {
            ProductVM productVm = new();
            productVm.CategoryList = _unitofwork.Category.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });
            productVm.CoverTypeList = _unitofwork.CoverType.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });
            //ProductVM productVM = new()
            //{
            //    Product = new(),
            //    //CategoryList = _unitofwork.Category.GetAll().Select(
            //    //u => new SelectListItem
            //    //{
            //    //    Text = u.Name,
            //    //    Value = u.Id.ToString()
            //    //}),
            //    CategoryList = _unitofwork.Category.GetAll().Select(
            //        i => new SelectListItem
            //        {
            //            Text = i.Name,
            //            Value = i.Id.ToString()
            //        }),
            //    CoverTypeList = (IEnumerable<CoverType>)_unitofwork.CoverType.GetAll().Select(
            //    u => new SelectListItem
            //    {
            //        Text = u.Name,
            //        Value = u.Id.ToString()
            //    })

            //};
            //Product product = new();
            //IEnumerable<SelectListItem> categoryList = _unitofwork.Category.GetAll().Select(
            //    u => new SelectListItem
            //    {
            //        Text = u.Name,
            //        Value = u.Id.ToString()
            //    });
            //IEnumerable<SelectListItem> covertypeList = _unitofwork.CoverType.GetAll().Select(
            //   u => new SelectListItem
            //   {
            //       Text = u.Name,
            //       Value = u.Id.ToString()
            //   });
            if (id == null ||id==0)
            {
                //Create the Product
                //return NotFound();
                //ViewBag.categoryList = categoryList;
                //ViewBag.covertypeList = covertypeList;
                return View(productVm);
            }
            else
            {
                //Update the product
                productVm.Product=_unitofwork.Product.GetFirstorDefault(u=>u.Id==id);
                return View(productVm);
                

            }
            //var edit = _Db.GetFirstorDefault(x => x.Name == "id");
            //var edit = _unitofwork.Product.GetFirstorDefault(x => x.Id == id);

            //if (edit == null)
            //{
            //    return NotFound();
            //}

            //return View(edit);
            
            return View(productVm);
        }

        [HttpPost]
        public IActionResult Upsert(ProductVM p, IFormFile? file)
        {
            
                string wwwRootPath = _hostEnvironment.WebRootPath;

                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(wwwRootPath, @"Images\Products\");
                    var extension = Path.GetExtension(file.FileName);
                if (p.Product.ImageUrl != null)
                {
                    var oldImagePath = Path.Combine(wwwRootPath, p.Product.ImageUrl.TrimStart('\\'));
                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }
                    using (var filestreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                    {
                        file.CopyTo(filestreams);
                    }
                    p.Product.ImageUrl = @"\Images\Products\" + fileName + extension;
                }
            if (p.Product.Id == 0) 
            {
                _unitofwork.Product.Add(p.Product);
            }
            else
            {
                _unitofwork.Product.Update(p.Product);
            }
                _unitofwork.Save();
                TempData["Success"] = "Product Created Successfuly";
                return RedirectToAction("Index");
            
        }


        //[HttpGet]
        //public IActionResult Delete(int? id)
        //{
        //    //var edit = _Db.Categories.Where(x => x.Id == id).FirstOrDefault();
        //    var productfromdbfirst = _unitofwork.Product.GetFirstorDefault(x => x.Id == id);
        //    if (productfromdbfirst == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(productfromdbfirst);
        //}

        //[HttpPost]
        //public IActionResult Delete(Product p)
        //{
        //    _unitofwork.Product.Remove(p);
        //    _unitofwork.Save();
        //    TempData["Success"] = "Cover Type Deleted Successfuly";
        //    return RedirectToAction("Index");
        //}

        #region
        [HttpGet]
        public IActionResult GetAll()
        {
            //var a = HttpContext.Request.Headers;
            //int b = Int32.Parse("asd");
           
            var productList = _unitofwork.Product.GetAll(includeProperties:"Category,CoverType");
            return Json(new { data = productList });
            //return Ok(new {data = productList });
            //return Ok(productList);
        }


        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var obj = _unitofwork.Product.GetFirstorDefault(u=>u.Id == id);
            if(obj == null)
            {
                return Json(new {success=false, message="Error While Deleting"});
            }
            if (obj.ImageUrl != null)
            {
                var oldImagePath = Path.Combine(_hostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));
                if (System.IO.File.Exists(oldImagePath))
                {
                    System.IO.File.Delete(oldImagePath);
                }
            }
            _unitofwork.Product.Remove(obj);
            _unitofwork.Save();
            return Json(new { success = false, message = "Delete Successfuly" });

        }
        #endregion

    }
}

BulkyBookWeb/Controllers/CategoryController.cs
using BulkyBook.Models;
using BulkyBookWeb.Data;

using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BulkyBookWeb.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _Db;
        public CategoryController(ApplicationDbContext db)
        {
            _Db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Category> categories = _Db.Categories.ToList();

            return View(categories);
        }
        [HttpGet]
        public IActionResult Create()
        { 
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category obj)
        {
            if (obj.Name == obj.DisplayOrder)
            {
                ModelState.AddModelError("CustomError", "The Display Order Cannot Exactly same as Category Name");
            }

            if (ModelState.IsValid)
            {
                _Db.Categories.Add(obj);
                _Db.SaveChanges();
                TempData["Success"] = "Category Created Successfuly";
                return RedirectToAction("Index");
            }

           

            return View(obj);
        }
        [HttpGet]
        public IActionResult Details(int id)
        {
           var details = _Db.Categories.Where(x => x.Id == id).FirstOrDefault();
       
            return View(details);
        }
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }
            var edit = _Db.Categories.Where(x => x.Name == "id").FirstOrDefault();

            if(edit == null)
            {
                return NotFound();
            }

            return View(edit);
        }

        [HttpPost]
        public IActionResult Edit(Category ctrg)
        {
            _Db.Categories.Update(ctrg);
            _Db.SaveChanges();
            TempData["Success"] = "Category Updated Successfuly";
            return RedirectToAction("Index");
        }


        [HttpGet]
        public IActionResult Delete(int? id)
        {
           var edit = _Db.Categories.Where(x => x.Id == id).FirstOrDefault();

           return View(edit);
        }

        [HttpPost]
        public IActionResult Delete(Category ctrg)
        {
            _Db.Categories.Remove(ctrg);
            _Db.SaveChanges();
            TempData["Success"] = "Category Deleted Successfuly";
            return RedirectToAction("Index");
        }


    }
}

BulkyBookWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BulkyBookWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="~/BulkyBookWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BootsWatchTheme/BootsWatch.css" asp-append-version="true"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css"/>
    <link rel="stylesheet" href="~\css\tostr.css"/>
    <link rel="stylesheet" href="//cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css"/>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link active" href="#">
                                Home
                                <span class="visually-hidden">(current)</span>
                            </a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="Category" asp-action="Index">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="CoverType" asp-action="Index">Cover Types</a>
                        </li>*@

                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Content Managment</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Categories</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="CoverType" asp-action="Index">Cover Types</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Products</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Companies</a>
                               @* <a class="dropdown-item" href="#">Action</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <a class="dropdown-item" href="#">Something else here</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Separated link</a>*@
                            </div>
                        </li>
                        <partial name="_LoginPartial"/>
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-sm-2" type="text" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
       @* <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BulkyBookWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>*@
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
           
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BulkyBookWeb - <a asp-area="Customer" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @*<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="~//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="//cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="https://cdn.tiny.cloud/1/5j9kujb3rr70hxjt37gixvm2lmzy98yln7gzhkgyodwkj8a9/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    @*<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>*@
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BulkyBookWeb/Views/Shared/_Notification.cshtml
@if (TempData["Success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    <script type="text/javascript">
        toastr.success('@TempData["Success"]')
    </script>
   
}

@if (TempData["Error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["Error"]')
    </script>
    
}